---
- name: Despliegue de pagina web
  hosts: servers
  become: true
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copiar Archivo
      copy:
        src: index.html
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'